Test/soraya
Bay-Valley-Tech-Code-Academy/UI-Tool-Kit pull request #12
Opened 2024-08-14 20:52 UTC by sorayaboza

## Changes
_List Changes Introduced by this PR_
1. Replaced products.js with postgres.js.
2. Updated readme with instructions for running the app with PostgreSQL.

## Purpose
Introduce backend features to the app.

## Approach
Database allows for a larger set of items for our product list.

## Learning

Installing vs code with postgres: https://www.youtube.com/watch?v=ezjoDYs72GA

Connecting postgres database to the nextjs app:
 https://www.youtube.com/watch?v=EWo6dpy7tB8

Closes #000

2024-08-15 19:24 UTC, missile720 requested changes
Looks good just add the .env file to .gitignore

2024-08-15 19:24 UTC, missile720 commented on .env
This file should be in gitignore for security reasons. Looks like its just a sample so it should be fine

2024-08-15 22:20 UTC, jm2601 approved these changes
Looks good. I have some trouble getting the DB to work because Mac issues however, these changes also fixed issue #19 .

2024-08-17 18:43 UTC, missile720 approved these changes
Looks good!

2024-08-17 18:43 UTC, merged